spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: codingCamp
  datasource:
    url: jdbc:postgresql://localhost:15001/codingCamp
    username: postgres
    password: secret99

flask:
  api:
    url: https://learntic-production.up.railway.app/predict
    timeout: 30000
    retry:
      max: 3

batch:
  processing:
    delay: 100

logging:
  level:
    com.example.codingCamp.prediction: DEBUG
