spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: codingCamp

  datasource:
    # url: jdbc:postgresql:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      initialization-fail-timeout: -1