spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: codingCamp
  datasource:
    # url: ${DATABASE_URL_DEV}
    url: jdbc:postgresql://localhost:15001/codingCamp
    username: postgres
    password: secret99

# Flask API URL (pindah ke level root, bukan di bawah datasource)
flask:
  api:
    url: https://learntic-production.up.railway.app/predict

# Logging configuration (pindah ke level root)
logging:
  level:
    com.example.codingCamp.prediction: DEBUG